export const QueryKeys = {
  user: "user",
  subjects: "subjects",
  singleSubject: "singleSubject",
  roles: "roles",
  singleRole: "singleRole",
  customRole: "customRole",
  systemRole: "sytemRole",
  permissions: "permissions",
  permissionId: "permissionId",
  subjectTopics: "subjectTopics",
  topicById: "topicById",
  questionsById: "questionsById",
  questionDetails: "questionDetails",
} as const;
